test_that("plot_denmark properly creates nice plots", {
  skip_on_ci()

  expect_no_error(plot_denmark())
  expect_no_error(plot_denmark(fill = "navn"))
  expect_no_error(plot_denmark(fill = "names"))
  expect_no_error(plot_denmark(fill = "green"))
  expect_no_error(plot_denmark(fill = "navn", color = "dagi_id"))
  expect_no_error(plot_denmark(fill = "navn", color = "green"))
  expect_no_error(plot_denmark(fill = "green", color = "navn"))
  expect_no_error(plot_denmark(fill = "green", color = "green"))
  expect_no_error(plot_denmark(color = "green"))
  expect_no_error(plot_denmark(color = "navn"))

  vdiffr::expect_doppelganger("Denmark", plot_denmark())
  vdiffr::expect_doppelganger("Fill navn", plot_denmark(fill = "navn"))
  vdiffr::expect_doppelganger("Fill names", plot_denmark(fill = "names"))
  vdiffr::expect_doppelganger("Fill green", plot_denmark(fill = "green"))
  vdiffr::expect_doppelganger("Fill navn color dagi_id", plot_denmark(fill = "navn", color = "dagi_id"))
  vdiffr::expect_doppelganger("Fill navn color navn", plot_denmark(fill = "navn", color = "navn"))
  vdiffr::expect_doppelganger("Fill navn color green", plot_denmark(fill = "navn", color = "green"))
  vdiffr::expect_doppelganger("Fill green color navn", plot_denmark(fill = "green", color = "navn"))
  vdiffr::expect_doppelganger("Fill green color green", plot_denmark(fill = "green", color = "green"))
  vdiffr::expect_doppelganger("Color green", plot_denmark(color = "green"))
  vdiffr::expect_doppelganger("Color navn", plot_denmark(color = "navn"))
})
